# Generated by Django 5.1.1 on 2025-03-13 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(default='')),
                ('date_opened', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('workshop_type', models.CharField(choices=[('MC', 'Motorcycle'), ('CR', 'Car'), ('BT', 'Bus/Truck'), ('OT', 'Other')], max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='rating',
            name='bikeworkshop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workshoprepair'),
        ),
        migrations.DeleteModel(
            name='BikeWorkshop',
        ),
    ]
