# Generated by Django 5.1.1 on 2025-03-16 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workshoprepair_alter_rating_bikeworkshop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='bikeworkshop',
            new_name='workshoprepair',
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('datetime', models.DateTimeField()),
                ('workshoprepair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workshoprepair')),
            ],
        ),
    ]
