# Generated by Django 5.1.1 on 2025-03-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workshoprepair_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshoprepair',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
