# Generated by Django 5.1.1 on 2025-04-12 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_comment_delete_dummymodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='rating_value_validate', violation_error_message='Rating Invalid: Must Fall Between 1 And 5.'),
        ),
    ]
