# Generated by Django 5.1.1 on 2025-04-12 15:02

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_workshoprepair_validated_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoprepair',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[core.models.validator_workshoprepair_name_begins_with_a]),
        ),
    ]
