# Generated by Django 5.1.1 on 2025-04-12 15:10

import core.models
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_workshoprepair_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshoprepair',
            name='name',
            field=models.CharField(max_length=100, validators=[core.models.validator_workshoprepair_name_begins_with_a]),
        ),
        migrations.AddConstraint(
            model_name='workshoprepair',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='name_uniq_constraint'),
        ),
    ]
