# Generated by Django 5.1.1 on 2025-04-12 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rating_user_workshop_uniq'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='user_workshop_uniq',
        ),
    ]
