# Generated by Django 5.1.1 on 2024-10-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCustomer', models.CharField(max_length=50)),
                ('nameDriver', models.CharField(max_length=50)),
                ('destination', models.TextField()),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
