# Generated by Django 5.1.1 on 2024-09-29 04:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(choices=[('python', 'python'), ('django', 'django'), ('javascript', 'javascript')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
