# Generated by Django 5.1.1 on 2024-10-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='writer',
            field=models.CharField(default='admin', max_length=50),
            preserve_default=False,
        ),
    ]
