# Generated by Django 5.1.1 on 2024-10-16 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kontak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakmodel',
            name='dateTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
