# Generated by Django 5.1.1 on 2024-10-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='pubdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
