# Generated by Django 5.1.1 on 2024-10-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_artikel_pubdate_alter_artikel_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
