# Generated by Django 5.1.1 on 2024-09-29 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.publication'),
        ),
    ]
